"""
Destination seed data for all 12 ranked target countries + Global Reference Tables + India Baseline.
Includes live 2026 exchange rates, financial economics, sponsor visas, PR criteria, language requirements,
Quality of Life rankings, Happiness Index, Safety scores, Retirement suitability, Scenic/Pollution ratings,
Peaceful Scenic Living Motivation, Best City/State Recommendations, and practical "Keep in Mind" gotchas.
"""

# 🇮🇳 India Baseline Reference Data
INDIA_BASELINE = {
    "country_name": "India (Current Baseline)",
    "flag_emoji": "🇮🇳",
    "currency_code": "INR",
    "currency_symbol": "₹",
    "exchange_rate_inr": 1.0,
    "current_salary_monthly": 100000.0,  # ₹1 Lakh / month
    "current_salary_annual": 1200000.0,   # ₹12 Lakhs / year
    "estimated_tax_rate": 10.0,          # ~10% under New Tax Regime
    "monthly_tax": 10000.0,
    "monthly_take_home": 90000.0,        # ₹90,000 / month
    "monthly_expense": 40000.0,          # ₹40,000 / month living expenses
    "monthly_savings": 50000.0,          # ₹50,000 / month
    "annual_savings": 600000.0,          # ₹6.00 Lakhs / year
    "quality_of_life_rank": "#54 Worldwide",
    "happiness_rank": "#117 Worldwide (TheGlobalEconomy 2026 - Score: 4.39)",
    "safety_score": "Moderate (Score: 56.2/100)",
    "scenic_peace_note": "Rich Himalayan mountains & Kerala backwaters, but metropolitan tech centers (Bengaluru/NCR) face heavy air pollution (AQI 150–300+), traffic bottlenecks, and high civic density.",
    "best_cities_states": "• **Kerala (Munnar / Wayanad)** & **Himachal / Uttarakhand**: Breathtaking scenic hill stations and mountain retreats.\n• **Tech Centers**: Bengaluru / Pune / NCR for IT jobs.",
    "interview_style_summary": "Deep Hands-on Development Depth, Framework Internals, Live Debugging & Machine Coding (LLD)",
    "interview_process_stages": "1. Recruiter Screen (20m) → 2. Machine Coding Round (90m LLD: write working code with design patterns & tests) → 3. Problem Solving & DSA (60m) → 4. High-Level Distributed System Design (60m) → 5. Engineering Manager / Director (Culture & Past Projects)",
    "employer_behavior_culture": "Expects comprehensive knowledge of framework internals (Python GIL, AsyncIO, Django ORM / Spring JVM memory), query plans (EXPLAIN ANALYZE, indexing, locking), and ability to write end-to-end runnable code quickly. Panels often probe specific real-world incident handling, production firefighting, and hands-on debugging.",
    "senior_8yoe_focus": "For 8+ YOE (Lead / Staff): Expect deep architectural ownership, low-level design patterns (SOLID, Concurrency), past project deep-dives, database query tuning under high concurrency, cross-functional delivery leadership.",
    # Purchasing Power & Affordability Benchmark
    "standard_car_cost_inr": 2200000.0,  # ₹22 Lakhs (New standard sedan/SUV like Honda City/Creta)
    "car_months_salary": 24.4,          # Over 2 full years (24.4 months) of take-home salary
    "car_months_savings": 44.0,         # 44 months of full savings (~3.7 years)
    "iphone_work_days": 45.0,           # ~45 working days (~2 months) of entire take-home pay
    "purchasing_power_index": 64.2,     # Numbeo Local Purchasing Power
    "cost_of_living_index": 21.8,
}

# 🏆 Global Reference Lists (Synced directly from TheGlobalEconomy.com & Numbeo 2026)
TOP_10_HAPPINESS_COUNTRIES = [
    {"rank": 1, "country": "Finland", "flag": "🇫🇮", "score": "7.74", "is_target": False},
    {"rank": 2, "country": "Denmark", "flag": "🇩🇰", "score": "7.52", "is_target": False},
    {"rank": 3, "country": "Iceland", "flag": "🇮🇸", "score": "7.52", "is_target": False},
    {"rank": 4, "country": "Sweden", "flag": "🇸🇪", "score": "7.35", "is_target": True, "target_tag": "Target #6"},
    {"rank": 5, "country": "Netherlands", "flag": "🇳🇱", "score": "7.31", "is_target": True, "target_tag": "⭐ Priority #1"},
    {"rank": 6, "country": "Costa Rica", "flag": "🇨🇷", "score": "7.27", "is_target": False},
    {"rank": 7, "country": "Norway", "flag": "🇳🇴", "score": "7.26", "is_target": True, "target_tag": "Target #7"},
    {"rank": 8, "country": "Israel", "flag": "🇮🇱", "score": "7.23", "is_target": False},
    {"rank": 9, "country": "Luxembourg", "flag": "🇱🇺", "score": "7.12", "is_target": False},
    {"rank": 10, "country": "Mexico", "flag": "🇲🇽", "score": "6.98", "is_target": False},
    {"rank": 11, "country": "Australia", "flag": "🇦🇺", "score": "6.97", "is_target": True, "target_tag": "Target #8"},
    {"rank": 12, "country": "New Zealand", "flag": "🇳🇿", "score": "6.95", "is_target": True, "target_tag": "Target #9"},
    {"rank": 13, "country": "Switzerland", "flag": "🇨🇭", "score": "6.94", "is_target": True, "target_tag": "Target #5"},
    {"is_divider": True},
    {"rank": 15, "country": "Ireland", "flag": "🇮🇪", "score": "6.89", "is_target": True, "target_tag": "Target #10"},
    {"is_divider": True},
    {"rank": 18, "country": "Canada", "flag": "🇨🇦", "score": "6.80", "is_target": True, "target_tag": "⭐ Priority #1"},
    {"is_divider": True},
    {"rank": 22, "country": "Germany", "flag": "🇩🇪", "score": "6.75", "is_target": True, "target_tag": "⭐ Priority #1"},
    {"is_divider": True},
    {"rank": 24, "country": "USA", "flag": "🇺🇸", "score": "6.72", "is_target": True, "target_tag": "⭐ Priority #1"},
    {"is_divider": True},
    {"rank": 26, "country": "Poland", "flag": "🇵🇱", "score": "6.67", "is_target": True, "target_tag": "Target #11"},
    {"is_divider": True},
    {"rank": 33, "country": "Singapore", "flag": "🇸🇬", "score": "6.57", "is_target": True, "target_tag": "🥈 Tier-1 APAC"},
    {"is_divider": True},
    {"rank": 117, "country": "India", "flag": "🇮🇳", "score": "4.39", "is_target": True, "target_tag": "🇮🇳 Baseline"},
]

# 🚗 Quality of Life & Real-World Purchasing Power Index (Salary vs Cost of Living & Asset Multipliers)
PURCHASING_POWER_INDEX_DATA = [
    {
        "country": "USA",
        "flag": "🇺🇸",
        "is_priority": True,
        "monthly_take_home_inr": 986355.0,  # ~$10,350 / mo net
        "monthly_expense_inr": 428850.0,    # ~$4,500 / mo living
        "monthly_savings_inr": 557505.0,    # ~$5,850 / mo net savings
        "annual_savings_inr": 6690060.0,    # ₹66.90 L/year
        "standard_car_cost_local": "$26,000",
        "standard_car_cost_inr": "₹24.78 L",
        "car_months_salary": 2.5,           # ~2.5 Months of Net Salary!
        "car_months_savings": 4.4,          # ~4.4 Months of Net Savings
        "iphone_work_days": 2.5,            # Only 2.5 Days of Work
        "purchasing_power_index": 122.5,
        "cost_of_living_index": 72.4,
        "quality_of_life_score": 175.5,
        "affordability_verdict": "⚡ Fastest Asset Wealth Creation: Buy a brand new car in under 3 months of salary!",
    },
    {
        "country": "Switzerland",
        "flag": "🇨🇭",
        "is_priority": False,
        "monthly_take_home_inr": 1126288.0, # ~CHF 9,425 / mo net
        "monthly_expense_inr": 501900.0,   # ~CHF 4,200 / mo living
        "monthly_savings_inr": 624388.0,   # ~CHF 5,225 / mo savings
        "annual_savings_inr": 7492650.0,   # ₹74.93 L/year
        "standard_car_cost_local": "CHF 28,000",
        "standard_car_cost_inr": "₹33.46 L",
        "car_months_salary": 3.0,           # ~3.0 Months of Net Salary
        "car_months_savings": 5.4,          # ~5.4 Months of Net Savings
        "iphone_work_days": 2.8,            # Only 2.8 Days of Work
        "purchasing_power_index": 128.4,
        "cost_of_living_index": 112.0,
        "quality_of_life_score": 190.5,
        "affordability_verdict": "🏔️ Highest Disposable Savings: Pure alpine living with lowest European effective taxes.",
    },
    {
        "country": "Canada",
        "flag": "🇨🇦",
        "is_priority": True,
        "monthly_take_home_inr": 571453.0,  # ~CAD$ 8,312 / mo net
        "monthly_expense_inr": 261250.0,    # ~CAD$ 3,800 / mo living
        "monthly_savings_inr": 310203.0,    # ~CAD$ 4,512 / mo savings
        "annual_savings_inr": 3722438.0,    # ₹37.22 L/year
        "standard_car_cost_local": "CAD$ 32,000",
        "standard_car_cost_inr": "₹22.00 L",
        "car_months_salary": 3.8,           # ~3.8 Months of Net Salary
        "car_months_savings": 7.1,          # ~7.1 Months of Net Savings
        "iphone_work_days": 4.1,            # 4.1 Days of Work
        "purchasing_power_index": 98.6,
        "cost_of_living_index": 66.5,
        "quality_of_life_score": 164.8,
        "affordability_verdict": "🍁 High Purchasing Power + 5-Yr Continuous Super Visa stay for Mother & Family.",
    },
    {
        "country": "Netherlands",
        "flag": "🇳🇱",
        "is_priority": True,
        "monthly_take_home_inr": 648667.0,  # ~€5,833 / mo net (30% ruling)
        "monthly_expense_inr": 289120.0,    # ~€2,600 / mo living
        "monthly_savings_inr": 359547.0,    # ~€3,233 / mo savings
        "annual_savings_inr": 4314560.0,    # ₹43.15 L/year
        "standard_car_cost_local": "€27,000",
        "standard_car_cost_inr": "₹30.02 L",
        "car_months_salary": 4.6,           # ~4.6 Months of Net Salary
        "car_months_savings": 8.3,          # ~8.3 Months of Net Savings
        "iphone_work_days": 4.8,            # 4.8 Days of Work
        "purchasing_power_index": 102.8,
        "cost_of_living_index": 68.2,
        "quality_of_life_score": 198.4,
        "affordability_verdict": "🏆 #1 Worldwide Living Quality: World-leading bike infra, canals & 30% expat tax ruling.",
    },
    {
        "country": "Germany",
        "flag": "🇩🇪",
        "is_priority": True,
        "monthly_take_home_inr": 519412.0,  # ~€4,670 / mo net
        "monthly_expense_inr": 233520.0,    # ~€2,100 / mo living
        "monthly_savings_inr": 285892.0,    # ~€2,570 / mo savings
        "annual_savings_inr": 3430700.0,    # ₹34.31 L/year
        "standard_car_cost_local": "€26,000",
        "standard_car_cost_inr": "₹28.91 L",
        "car_months_salary": 5.5,           # ~5.5 Months of Net Salary
        "car_months_savings": 10.1,         # ~10.1 Months of Net Savings
        "iphone_work_days": 6.0,            # 6.0 Days of Work
        "purchasing_power_index": 105.4,
        "cost_of_living_index": 64.8,
        "quality_of_life_score": 184.2,
        "affordability_verdict": "🇩🇪 Superb Engineering Quality: 21-month fast PR, pristine alpine nature & high stability.",
    },
    {
        "country": "Singapore",
        "flag": "🇸🇬",
        "is_priority": False,
        "monthly_take_home_inr": 940250.0,  # ~S$12,537 / mo net
        "monthly_expense_inr": 337500.0,    # ~S$4,500 / mo living
        "monthly_savings_inr": 602750.0,    # ~S$8,037 / mo savings
        "annual_savings_inr": 7233000.0,    # ₹72.33 L/year
        "standard_car_cost_local": "S$125,000",
        "standard_car_cost_inr": "₹93.75 L",
        "car_months_salary": 10.0,          # High due to COE certificate
        "car_months_savings": 15.5,
        "iphone_work_days": 2.9,            # Only 2.9 Days of Work
        "purchasing_power_index": 92.4,
        "cost_of_living_index": 78.5,
        "quality_of_life_score": 153.9,
        "affordability_verdict": "🇸🇬 Direct Mother LTVP: Highest APAC take-home (~11.5% tax) & world's best public transit.",
    },
    {
        "country": "India (Baseline)",
        "flag": "🇮🇳",
        "is_priority": False,
        "monthly_take_home_inr": 90000.0,   # ₹90k / mo net
        "monthly_expense_inr": 40000.0,     # ₹40k / mo living
        "monthly_savings_inr": 50000.0,     # ₹50k / mo savings
        "annual_savings_inr": 600000.0,     # ₹6.00 L/year
        "standard_car_cost_local": "₹22,00,000",
        "standard_car_cost_inr": "₹22.00 L",
        "car_months_salary": 24.4,          # 🚨 24.4 Months (Over 2 Full Years of Salary!)
        "car_months_savings": 44.0,         # 🚨 44 Months (~3.7 Years of full savings)
        "iphone_work_days": 45.0,           # 🚨 45 Working Days (~2 months of full salary)
        "purchasing_power_index": 64.2,
        "cost_of_living_index": 21.8,
        "quality_of_life_score": 121.4,
        "affordability_verdict": "⚠️ High Asset Inflation: Takes 2+ full years of net salary to purchase the same standard car.",
    },
]

TOP_10_LIVING_QUALITY_COUNTRIES = [
    {"rank": 1, "country": "Netherlands", "flag": "🇳🇱", "score": "198.4", "is_target": True, "target_tag": "🥉 Target #3"},
    {"rank": 2, "country": "Denmark", "flag": "🇩🇰", "score": "194.2", "is_target": False},
    {"rank": 3, "country": "Luxembourg", "flag": "🇱🇺", "score": "192.8", "is_target": False},
    {"rank": 4, "country": "Oman", "flag": "🇴🇲", "score": "191.1", "is_target": False},
    {"rank": 5, "country": "Switzerland", "flag": "🇨🇭", "score": "190.5", "is_target": True, "target_tag": "Target #4"},
    {"rank": 6, "country": "Finland", "flag": "🇫🇮", "score": "189.6", "is_target": False},
    {"rank": 7, "country": "Austria", "flag": "🇦🇹", "score": "188.9", "is_target": False},
    {"rank": 8, "country": "Germany", "flag": "🇩🇪", "score": "184.2", "is_target": True, "target_tag": "🥇 Target #1"},
    {"rank": 9, "country": "Iceland", "flag": "🇮🇸", "score": "183.0", "is_target": False},
    {"rank": 10, "country": "Norway", "flag": "🇳🇴", "score": "181.8", "is_target": True, "target_tag": "Target #7"},
    {"rank": 11, "country": "Sweden", "flag": "🇸🇪", "score": "179.6", "is_target": True, "target_tag": "Target #6"},
    {"is_divider": True},
    {"rank": 14, "country": "Australia", "flag": "🇦🇺", "score": "177.3", "is_target": True, "target_tag": "Target #8"},
    {"rank": 15, "country": "New Zealand", "flag": "🇳🇿", "score": "176.8", "is_target": True, "target_tag": "Target #9"},
    {"rank": 16, "country": "USA", "flag": "🇺🇸", "score": "175.5", "is_target": True, "target_tag": "Target #12"},
    {"is_divider": True},
    {"rank": 26, "country": "Ireland", "flag": "🇮🇪", "score": "165.2", "is_target": True, "target_tag": "Target #5"},
    {"rank": 27, "country": "Canada", "flag": "🇨🇦", "score": "164.8", "is_target": True, "target_tag": "Target #11"},
    {"is_divider": True},
    {"rank": 36, "country": "Poland", "flag": "🇵🇱", "score": "158.4", "is_target": True, "target_tag": "Target #10"},
    {"is_divider": True},
    {"rank": 42, "country": "Singapore", "flag": "🇸🇬", "score": "153.9", "is_target": True, "target_tag": "🥈 Target #2"},
    {"is_divider": True},
    {"rank": 54, "country": "India", "flag": "🇮🇳", "score": "121.4", "is_target": True, "target_tag": "🇮🇳 Baseline"},
]

TOP_10_POLLUTION_FREE_SCENIC_COUNTRIES = [
    {"rank": 1, "country": "Iceland", "flag": "🇮🇸", "aqi": "AQI < 5", "is_target": False},
    {"rank": 2, "country": "Switzerland", "flag": "🇨🇭", "aqi": "AQI < 8", "is_target": True, "target_tag": "Target #4"},
    {"rank": 3, "country": "New Zealand", "flag": "🇳🇿", "aqi": "AQI < 6", "is_target": True, "target_tag": "Target #9"},
    {"rank": 4, "country": "Norway", "flag": "🇳🇴", "aqi": "AQI < 7", "is_target": True, "target_tag": "Target #7"},
    {"rank": 5, "country": "Finland", "flag": "🇫🇮", "aqi": "AQI < 5", "is_target": False},
    {"rank": 6, "country": "Austria", "flag": "🇦🇹", "aqi": "AQI < 10", "is_target": False},
    {"rank": 7, "country": "Sweden", "flag": "🇸🇪", "aqi": "AQI < 8", "is_target": True, "target_tag": "Target #6"},
    {"rank": 8, "country": "Germany", "flag": "🇩🇪", "aqi": "AQI < 15", "is_target": True, "target_tag": "🥇 Target #1"},
    {"rank": 9, "country": "Ireland", "flag": "🇮🇪", "aqi": "AQI < 10", "is_target": True, "target_tag": "Target #5"},
    {"rank": 10, "country": "Costa Rica", "flag": "🇨🇷", "aqi": "AQI < 12", "is_target": False},
    {"is_divider": True},
    {"rank": 12, "country": "Netherlands", "flag": "🇳🇱", "aqi": "AQI < 18", "is_target": True, "target_tag": "🥉 Target #3"},
    {"is_divider": True},
    {"rank": 14, "country": "Australia", "flag": "🇦🇺", "aqi": "AQI < 12", "is_target": True, "target_tag": "Target #8"},
    {"is_divider": True},
    {"rank": 18, "country": "Canada", "flag": "🇨🇦", "aqi": "AQI < 14", "is_target": True, "target_tag": "Target #11"},
    {"is_divider": True},
    {"rank": 28, "country": "Singapore", "flag": "🇸🇬", "aqi": "AQI < 35", "is_target": True, "target_tag": "🥈 Target #2"},
    {"is_divider": True},
    {"rank": 39, "country": "USA", "flag": "🇺🇸", "aqi": "AQI < 38", "is_target": True, "target_tag": "Target #12"},
    {"is_divider": True},
    {"rank": 48, "country": "Poland", "flag": "🇵🇱", "aqi": "AQI < 42", "is_target": True, "target_tag": "Target #10"},
    {"is_divider": True},
    {"rank": 135, "country": "India", "flag": "🇮🇳", "aqi": "AQI 150–300+", "is_target": True, "target_tag": "🇮🇳 Baseline"},
]

# 🏢 Company Archetypes & Interview Styles Comparison Matrix
COMPANY_ARCHETYPES = [
    {
        "archetype": "FAANG & US Big Tech",
        "tag": "Algorithmic & Scale Heavy",
        "companies": "Google, Meta, Amazon, Microsoft, Apple, Netflix",
        "dsa_weight": "Very High (40%)",
        "system_design_weight": "High (35%)",
        "real_dev_weight": "Low-Med (10%)",
        "behavioral_weight": "High (15%)",
        "interview_format": "Phone Screen (DSA) → Onsite Loop: 2x LeetCode Med/Hard + 2x Distributed System Design (HLD/LLD) + 1x Behavioral (STAR / Leadership Principles / Bar Raiser)",
        "senior_8yoe_focus": "Distributed consensus, failure domains, capacity planning (QPS/Storage), handling extreme ambiguity, cross-organizational influence, and unblocking multiple teams.",
        "employer_vibe": "Structured rubrics, fast-paced probing on time/space invariants, STAR-format stories with quantified metrics, zero tolerance for hand-waving on distributed bottlenecks.",
    },
    {
        "archetype": "EU Tech Giants & Scale-ups",
        "tag": "Pragmatic Architecture & Direct Debate",
        "companies": "Booking.com, Adyen, Zalando, ASML, Spotify, Miro, bol.com, Celonis, Delivery Hero",
        "dsa_weight": "Medium (20%)",
        "system_design_weight": "Very High (40%)",
        "real_dev_weight": "High (25%)",
        "behavioral_weight": "High (15%)",
        "interview_format": "Recruiter Screen → Practical Coding / Take-home PR Review → High-Level System Architecture & Trade-offs → Culture & Disagreement Defense Round",
        "senior_8yoe_focus": "Event-driven systems (Kafka), database sharding/partitioning, Domain-Driven Design (DDD), explicit trade-off matrices (cost vs latency vs maintainability), and architectural decision records (ADRs).",
        "employer_vibe": "Radical candor, flat hierarchy, and collaborative challenge. Interviewers want you to defend your ideas: 'I disagree with this architecture because...' Welcomes 'I don't know, but here's how I'd investigate it' over bluffing.",
    },
    {
        "archetype": "India Product Unicorns & Tech",
        "tag": "Real Development & Framework Internals",
        "companies": "Flipkart, Swiggy, Razorpay, Zepto, InMobi, PhonePe, BrowserStack",
        "dsa_weight": "High (30%)",
        "system_design_weight": "High (30%)",
        "real_dev_weight": "Very High (30%)",
        "behavioral_weight": "Medium (10%)",
        "interview_format": "Recruiter Screen → Machine Coding Round (90m LLD: write working code with design patterns & tests) → Problem Solving & DSA → HLD Distributed Architecture → EM / Past Projects",
        "senior_8yoe_focus": "Framework internals (Python GIL, AsyncIO, Django ORM / JVM memory & GC), DB query execution plans (EXPLAIN ANALYZE, indexing, lock contention), high-concurrency race condition prevention, and live debugging.",
        "employer_vibe": "Heavy focus on hands-on coding depth, low-level design patterns (SOLID), past production incident firefights, and rapid delivery under tight deadlines.",
    },
    {
        "archetype": "US Remote & High-Growth Startups",
        "tag": "Extreme Ownership & Async Velocity",
        "companies": "Stripe, Datadog, Coinbase, GitLab, Automattic, Supabase",
        "dsa_weight": "Medium (20%)",
        "system_design_weight": "High (35%)",
        "real_dev_weight": "High (30%)",
        "behavioral_weight": "High (15%)",
        "interview_format": "Technical Screen → Live Pair Programming & Bug Triage → Distributed Systems Architecture → Async RFC Writing / Leadership & Execution",
        "senior_8yoe_focus": "Ability to operate autonomously with minimal supervision, write crisp technical RFCs, balance tech debt against shipping speed, and design observable cloud systems.",
        "employer_vibe": "Asynchronous communication clarity, product intuition, high agency, bias for action, and customer obsession.",
    },
]

# 🎯 Senior/Staff (8+ YOE) Behavioral & Technical Playbook
SENIOR_8YOE_PLAYBOOK = {
    "disagreement_defense": {
        "title": "How to Disagree with an Interviewer Professionally",
        "quote": 'Be prepared to say: "I disagree with this architecture because..." and defend it with concrete trade-offs.',
        "good_example": '"I see why you\'re proposing a synchronous REST call between Service A and Service B for simplicity. However, at our projected peak load of 50,000 QPS, this introduces tight coupling, cascaded timeouts, and a single point of failure. I would recommend an asynchronous event stream via Kafka with idempotency keys. Even though it introduces eventual consistency and slight operational overhead, it decouples the write path and protects our 99.99% availability SLA."',
        "bad_example": '"No, that\'s a bad design. Microservices shouldn\'t talk synchronously."',
        "rule": "Always frame disagreement in terms of system constraints (SLA, latency, blast radius, operational cost), never personal preference.",
    },
    "investigation_framework": {
        "title": "Handling Unknowns: The 4-Step Investigation Framework",
        "quote": 'Dutch & EU companies value people who can say: "I don\'t know, but here\'s how I would investigate it." That\'s much better than bluffing.',
        "steps": [
            {"step": "1. Acknowledge Transparently", "desc": '"I haven\'t worked with this specific database engine in a production setting at multi-terabyte scale."'},
            {"step": "2. Formulate Hypotheses", "desc": '"Based on general storage engine principles (LSM-trees vs B-Trees), the bottleneck is likely either write amplification during compaction or lock contention on hot partitions."'},
            {"step": "3. Detail the Investigation Plan", "desc": '"Here is how I would investigate: 1) Inspect query execution metrics and slow query logs; 2) Profile CPU vs disk I/O wait times; 3) Set up synthetic load tests in staging with realistic p99 traffic patterns."'},
            {"step": "4. Propose Fallback & Mitigations", "desc": '"In the interim, I would implement circuit breakers and read replicas to isolate blast radius while debugging."'},
        ]
    },
    "tradeoff_dimensions": [
        {"dimension": "Latency vs Throughput", "insight": "Batching increases throughput at the expense of per-item latency. Caching reduces latency but adds cache invalidation complexity."},
        {"dimension": "Consistency vs Availability (CAP)", "insight": "Financial ledgers require strong consistency (CP / 2PC / Raft), whereas social feeds and activity counters tolerate eventual consistency (AP / CRDTs)."},
        {"dimension": "Operational Cost vs Engineering Effort", "insight": "Managed services (AWS Aurora / DynamoDB) cost more per GB but reduce SRE maintenance toil; self-hosted clusters offer fine-grained tuning at high operational overhead."},
        {"dimension": "Simplicity vs Extensibility", "insight": "Avoid premature abstraction. Design for today's 10x scale with clean interfaces so the architecture can be evolved when reaching 100x scale."},
    ]
}

DESTINATIONS_DATA = [
    {
        "rank": 1,
        "country_name": "Germany",
        "flag_emoji": "🇩🇪",
        "summary_verdict": "⭐ Tier-1 Priority: Best overall EU engineering ecosystem, structured tech hubs & 21-month fast PR",
        "currency_code": "EUR",
        "currency_symbol": "€",
        "exchange_rate_inr": 111.20,
        "salary_min": 85000.0,
        "salary_max": 120000.0,
        "salary_median": 95000.0,
        "estimated_tax_rate": 41.0,
        "monthly_expense_local": 2100.0,
        "sponsor_visa_pathway": "EU Blue Card (Blaue Karte EU) via direct tech employer sponsorship. Fast-track approval (2–4 weeks) for shortage IT roles (salary threshold ~€45.3k). No labour market test required.",
        "pr_criteria_timeline": "Fast-Track Settlement Permit (Niederlassungserlaubnis) in 21 months with German B1, or 27 months with basic German A1. Full citizenship possible in 3–5 years under new nationality law.",
        "language_requirements": "English is 100% sufficient for tech roles & daily IT work. German A1–B1 needed for accelerated PR and public administration.",
        "family_mother_feasibility": "Spouse & kids get immediate full work rights. Parents can visit on 90-day/180-day multi-entry Schengen visitor visas (permanent stay requires exceptional hardship under §36(2) AufenthG).",
        "family_mother_badge": "Schengen Visitor Visa",
        "quality_of_life_rank": "#8 Worldwide",
        "happiness_rank": "#22 Worldwide (TheGlobalEconomy 2026 - Score: 6.75)",
        "safety_score": "Very High Safety · Low Violent Crime (Score: 71.5/100)",
        "retirement_suitability": "Exceptional statutory healthcare system (GKV), robust statutory pension with bilateral totalization agreements, quiet suburban green towns, and highly walkable cities with punctual regional trains.",
        "scenic_pollution_rating": "Pristine Air Quality (AQI: 10–25). 32% forest coverage (Black Forest, Bavarian Alps, Harz National Park, Lake Constance). Clean alpine tap water and strict green environmental laws.",
        "peaceful_scenic_motivation": "Immerse in peaceful alpine tranquility. Live within reach of the majestic Bavarian Alps (Garmisch-Partenkirchen, Berchtesgaden), the crystal waters of Lake Constance (Bodensee), or the pine-scented trails of the Black Forest (Schwarzwald). Germany cherishes a culture of deep quietude (Ruhezeit), Sunday nature walks (Sonntagsspaziergang), and 32% protected forest greenery.",
        "best_cities_states": "• **Bavaria (Munich & Garmisch-Partenkirchen foothills)**: Germany's premier tech capital (SAP, BMW, Personio, Celonis, Google/Apple engineering hubs) with direct 45-min train access to the Bavarian Alps, Lake Starnberg, and Black Forest nature.\n• **Baden-Württemberg (Stuttgart & Karlsruhe)**: High engineering compensation, lush green valleys, and peaceful Black Forest border towns.",
        "keep_in_mind_notes": "1) Heavy reliance on postal paper letters (Briefe / Papierkrieg); 2) Apartment hunting (Wohnungssuche) and city registration (Anmeldung) is notoriously competitive in Berlin/Munich; 3) Unfurnished rentals often lack a kitchen—tenants must buy/install an Einbauküche (EBK); 4) Everything except restaurants closes on Sundays (Ruhetag); 5) Church tax (Kirchensteuer) is automatically deducted unless officially deregistered.",
        "interview_style_summary": "Structured Engineering Precision, Domain-Driven Design (DDD), Clean Architecture & Production Rigor",
        "interview_process_stages": "Stage 1: Talent Partner / Screening (30m) → Stage 2: Practical Coding / Take-Home PR Review (60m) → Stage 3: High-Level System Architecture & Domain Modeling (60m) → Stage 4: Engineering Excellence, Mentorship & Collaboration (45m)",
        "employer_behavior_culture": "Methodical, structured, and punctually organized. German interviewers prioritize long-term system maintainability, clean boundaries, test pyramid discipline, and explicit documentation (ADRs). Direct and constructive feedback is standard.",
        "senior_8yoe_focus": "For 8+ YOE: Expect deep discussions on Domain-Driven Design (DDD), bounded contexts, CI/CD pipeline reliability, data privacy (GDPR compliance), architectural decision records (ADRs), and mentoring junior/mid developers.",
        "tax_breakdown_notes": "Progressive income tax (Class 1) + 5.5% solidarity surcharge + social security (~18.6% pension, 14.6% health, 3.4% nursing care split 50/50 with employer).",
        "tech_market_notes": "Strong enterprise & AI startup presence in Berlin & Munich (Delivery Hero, Zalando, Personio, Celonis, SAP, Siemens, Amazon/Google hubs).",
        "order_index": 1,
    },
    {
        "rank": 2,
        "country_name": "Netherlands",
        "flag_emoji": "🇳🇱",
        "summary_verdict": "⭐ Tier-1 Priority: #1 Living Quality worldwide, 30% expat tax ruling & premier global tech hubs",
        "currency_code": "EUR",
        "currency_symbol": "€",
        "exchange_rate_inr": 111.20,
        "salary_min": 85000.0,
        "salary_max": 125000.0,
        "salary_median": 100000.0,
        "estimated_tax_rate": 30.0,
        "monthly_expense_local": 2600.0,
        "sponsor_visa_pathway": "Highly Skilled Migrant (Kennismigrant) visa through IND recognized sponsor employer (processed in 2–3 weeks).",
        "pr_criteria_timeline": "Permanent Residence (or EU Long-Term Residence) after 5 consecutive years of continuous legal residence + passing the Dutch Civic Integration Exam (Inburgeringsexamen).",
        "language_requirements": "English is ubiquitous (>95% proficiency in tech and daily life). Dutch (A2/B1 level) required only for permanent residency integration test.",
        "family_mother_feasibility": "Spouse receives unrestricted right to work. Parents can visit on 90-day Schengen visitor visas (permanent stay requires sole dependency proof).",
        "family_mother_badge": "Schengen Visitor Visa",
        "quality_of_life_rank": "🏆 #1 Worldwide (Numbeo 2026)",
        "happiness_rank": "🏆 #5 Worldwide (TheGlobalEconomy 2026 - Score: 7.31)",
        "safety_score": "Extremely High Safety · World Top 25 (Score: 78.2/100)",
        "retirement_suitability": "World's #1 Quality of Life index. Flat terrain ideal for senior cycling, top-tier universal healthcare, excellent elder community support, peaceful historic canals and windmill villages.",
        "scenic_pollution_rating": "Clean North Sea coastal breeze, expansive tulip fields, vast national parks (De Hoge Veluwe), extensive canal waterways, and world's highest density of car-free bicycle greenways.",
        "peaceful_scenic_motivation": "Idyllic, quiet living with world-class canal charm. Experience the car-free peace of Giethoorn ('Venice of the North'), cycle through endless vibrant tulip fields in springtime, explore the quiet heather dunes of De Hoge Veluwe National Park, and enjoy breezy North Sea coastal beaches with zero traffic noise.",
        "best_cities_states": "• **Utrecht (Province of Utrecht)**: The heart of the Netherlands—historic car-free tree-lined canals, top cycling infrastructure, and quieter family living only 25 mins by train from Amsterdam.\n• **Eindhoven (Brainport / North Brabant)**: High-tech silicon capital (ASML, Philips, NXP) surrounded by the serene green Kempen countryside and forested nature parks.",
        "keep_in_mind_notes": "1) Severe acute housing crisis (Woningnood) in Randstad (Amsterdam, Utrecht, The Hague); 2) Frequent rainy, overcast, and windy cycling weather; 3) Family Doctor / GP (Huisarts) acts as strict gatekeeper for specialized care (Paracetamol-first approach); 4) Expat 30% tax ruling has been subject to phased legislative caps.",
        "interview_style_summary": "Direct Egalitarian Discussion, Architectural Trade-off Defense, Pragmatic Code Reviews & Zero-Bluff Transparency",
        "interview_process_stages": "Stage 1: Recruiter Screen (30m) → Stage 2: Technical Take-Home / Live Pair Programming / PR Review (60m) → Stage 3: High-Level System Architecture & Trade-offs (60m) → Stage 4: Behavioral & Culture Fit (Directness, Autonomy & Collaboration, 45m)",
        "employer_behavior_culture": "Radical candor and flat hierarchy. Dutch interviewers welcome constructive disagreement! Be prepared to say: 'I disagree with this architecture because...' and defend it with concrete trade-offs (cost, latency, complexity, maintenance). Transparency is paramount: saying 'I don't know, but here's how I would investigate it' is rewarded far above bluffing.",
        "senior_8yoe_focus": "For 8+ YOE: Focus on communication, extreme autonomy, collaborative debate, explicit trade-off matrices, psychological safety, and proving how you empower team members rather than commanding them.",
        "tax_breakdown_notes": "Expat 30% Ruling grants a 30% tax-free allowance on gross income for qualifying foreign hires, reducing effective tax to ~30%. Standard box 1 progressive tax is 36.97% to 49.50%.",
        "tech_market_notes": "Major European tech hub: Booking.com, Uber EMEA HQ, ASML, Adyen, Miro, Databricks, Optiver, Flow Traders.",
        "order_index": 2,
    },
    {
        "rank": 3,
        "country_name": "USA",
        "flag_emoji": "🇺🇸",
        "summary_verdict": "⭐ Tier-1 Priority: World's highest compensation upside, fastest asset purchasing power & AI innovation",
        "currency_code": "USD",
        "currency_symbol": "$",
        "exchange_rate_inr": 95.30,
        "salary_min": 150000.0,
        "salary_max": 220000.0,
        "salary_median": 180000.0,
        "estimated_tax_rate": 31.0,
        "monthly_expense_local": 4500.0,
        "sponsor_visa_pathway": "H-1B Specialty Occupation Visa (annual lottery or cap-exempt transfer), L-1A/L-1B Intra-Company Transfer (AllianceTek / Denali US placement bridge), or O-1A.",
        "pr_criteria_timeline": "Employment-Based Green Card (EB-2 / EB-3) has backlogs for Indian-born applicants; EB-1A Extraordinary Ability or EB-2 NIW for fast-track.",
        "language_requirements": "English. 100% native English environment, zero language barrier.",
        "family_mother_feasibility": "Parents can visit on B1/B2 Visitor Visa (up to 6 months continuous per entry with travel medical insurance). No permanent resident dependent category.",
        "family_mother_badge": "B1/B2 Visitor Visa",
        "quality_of_life_rank": "#16 Worldwide",
        "happiness_rank": "#24 Worldwide (TheGlobalEconomy 2026 - Score: 6.72)",
        "safety_score": "Moderate · Highly Variable by Neighborhood (Score: 61.0/100)",
        "retirement_suitability": "World's most advanced specialized medicine and top tertiary hospitals (Mayo Clinic, Johns Hopkins), Florida/Texas warm weather retirement communities, huge 401(k)/IRA investment potential.",
        "scenic_pollution_rating": "Grand National Parks (Yellowstone, Yosemite, Grand Canyon), Pacific Coast Highway, California sunshine, vast regional natural diversity.",
        "peaceful_scenic_motivation": "Grand national park sanctuaries and scenic wonderlands. Discover immense peace among the evergreen forests of the Pacific Northwest (Washington & Oregon), the awe-inspiring granite monoliths and waterfalls of Yosemite Valley, the crystal alpine shores of Lake Tahoe, or the misty tranquility of the Great Smoky Mountains.",
        "best_cities_states": "• **Washington State (Seattle Eastside: Bellevue, Redmond, Kirkland)**: 0% state income tax, world's highest tech salaries (Microsoft, Amazon, Google, Meta), surrounded by Lake Washington, Lake Sammamish, and Mount Rainier views.\n• **California (Orange County / Irvine & San Diego - La Jolla)**: Top safety rankings in the US, pristine Pacific beaches, sunny Mediterranean climate, and biotech/tech hubs.",
        "keep_in_mind_notes": "1) Private employer healthcare with complex deductibles, co-pays, and out-of-pocket maximums; 2) At-will employment with zero statutory notice periods or mandatory severance in layoffs; 3) Extreme safety and crime rate variations depending on city zip codes; 4) Heavy car-dependency with minimal public transit outside NYC/Chicago; 5) Decades-long backlogs for Indian-born Green Card applicants.",
        "interview_style_summary": "FAANG / High-Growth Startup Archetypes: Algorithmic Prowess (LeetCode Medium/Hard), High-Scale System Design, Business Impact & STAR Leadership",
        "interview_process_stages": "Stage 1: Recruiter Screen (30m) → Stage 2: Technical Phone Screen (45m DSA) → Stage 3: Full Onsite Loop: 2x Coding/DSA Rounds + 2x System Design (HLD/LLD) + 1x Behavioral (Bar Raiser / LP)",
        "employer_behavior_culture": "High bar for crisp communication, speed of thought, and structured problem framing. Expect fast-paced probing into scale constraints, failure scenarios, and measurable business impact.",
        "senior_8yoe_focus": "For 8+ YOE (Staff/Senior): Scope of impact, handling undefined requirements, driving consensus across 3+ teams, system capacity estimation, and cost-benefit trade-offs.",
        "tax_breakdown_notes": "Federal Income Tax (10% to 37%) + State Income Tax (e.g. PA 3.07%, CA up to 13.3%, WA/TX 0%) + FICA (6.2% Social Security + 1.45% Medicare).",
        "tech_market_notes": "World's premier AI & tech capital: Silicon Valley, NYC, Seattle, Austin, Boston with unmatched total comp (base + equity/RSUs).",
        "order_index": 3,
    },
    {
        "rank": 4,
        "country_name": "Canada",
        "flag_emoji": "🇨🇦",
        "summary_verdict": "⭐ Tier-1 Priority: Super Visa for mother (5-yr stay), high purchasing power & strong tech ecosystem",
        "currency_code": "CAD",
        "currency_symbol": "CAD$",
        "exchange_rate_inr": 68.75,
        "salary_min": 135000.0,
        "salary_max": 180000.0,
        "salary_median": 150000.0,
        "estimated_tax_rate": 33.5,
        "monthly_expense_local": 3800.0,
        "sponsor_visa_pathway": "Global Talent Stream (GTS) employer-sponsored work permit (2-week fast-track processing) or Intra-Company Transfer (ICT).",
        "pr_criteria_timeline": "Express Entry via Canadian Experience Class (CEC) or Provincial Nominee Program (OINP Tech / BC PNP Tech) after 1 year of Canadian skilled tech experience.",
        "language_requirements": "English (IELTS General / CELPIP CLB 7 to 9+ for PR points).",
        "family_mother_feasibility": "High: Canada Super Visa allows parents and grandparents to stay continuously in Canada for up to 5 years per entry (and extendable up to 7 years) with valid private health insurance.",
        "family_mother_badge": "Super Visa (5-Yr Stay)",
        "quality_of_life_rank": "#27 Worldwide",
        "happiness_rank": "#18 Worldwide (TheGlobalEconomy 2026 - Score: 6.80)",
        "safety_score": "High Safety · Peaceful Society (Score: 71.0/100)",
        "retirement_suitability": "Universal public healthcare (Medicare), multicultural and welcoming Indian diaspora, CPP/OAS pension security, peaceful lakefront cottages and suburban retirement communities.",
        "scenic_pollution_rating": "Breathtaking Rocky Mountains (Banff, Jasper), Niagara region, thousands of pristine freshwater lakes, vast pine forests, crisp northern air quality.",
        "peaceful_scenic_motivation": "Limitless wilderness tranquility and majestic mountain wonder. Marvel at the postcard-perfect turquoise waters of Lake Louise and Moraine Lake in Banff/Jasper, explore the ancient temperate rainforests of Vancouver Island, and experience peaceful lakefront cottage living beside millions of mirror-clear freshwater lakes.",
        "best_cities_states": "• **British Columbia (Greater Vancouver: North Vancouver & Burnaby)**: Flanked by the Pacific Ocean and towering coastal mountains, mildest snow-free winters in Canada, and year-round green nature.\n• **Ontario (Waterloo & Oakville)**: Canada's 'Silicon Valley of the North' (Shopify, Google, BlackBerry heritage) combined with quiet, safe lakefront living along Lake Ontario.",
        "keep_in_mind_notes": "1) Brutal, long freezing winters with temperatures dropping to -20°C to -30°C and heavy snow in Ontario/Quebec/Prairies; 2) Severe housing price and rental spikes in Greater Toronto and Vancouver; 3) Long ER and specialist wait times in provincial public healthcare; 4) Elevated cost of mobile plans and domestic air travel.",
        "interview_style_summary": "Hybrid US Big Tech & Collaborative Scale-Up: Algorithmic Fundamentals, Practical Architecture & Leadership",
        "interview_process_stages": "Stage 1: Recruiter Call (30m) → Stage 2: Technical Assessment / Live DSA (45-60m) → Stage 3: Virtual Onsite: System Design + Deep Dive + Behavioral Leadership (3-4 rounds)",
        "employer_behavior_culture": "Polite, structured, and focused on practical impact. Interviewers look for clear communication, structured problem-solving, and collaborative decision-making.",
        "senior_8yoe_focus": "For 8+ YOE: System reliability, microservice decoupling, handling ambiguous customer requirements, and cross-functional technical leadership.",
        "tax_breakdown_notes": "Combined Federal (15% to 33%) and Provincial tax (e.g. Ontario 5.05% to 13.16% + surtax) + CPP (Canada Pension Plan) and EI (Employment Insurance).",
        "tech_market_notes": "Large tech hubs in Toronto-Waterloo corridor, Vancouver, and Montreal: Shopify, 1Password, Amazon, Google, Microsoft, Wealthsimple.",
        "order_index": 4,
    },
    {
        "rank": 5,
        "country_name": "Singapore",
        "flag_emoji": "🇸🇬",
        "summary_verdict": "🥈 Tier-1 APAC: Best mother sponsorship (Direct LTVP), ultra-safe tropical Garden City & 11.5% tax",
        "currency_code": "SGD",
        "currency_symbol": "S$",
        "exchange_rate_inr": 75.00,
        "salary_min": 145000.0,
        "salary_max": 210000.0,
        "salary_median": 170000.0,
        "estimated_tax_rate": 11.5,
        "monthly_expense_local": 4500.0,
        "sponsor_visa_pathway": "Employment Pass (EP) sponsored by hiring employer (evaluated via COMPASS points framework) or Tech.Pass / ONE Pass for top earners.",
        "pr_criteria_timeline": "Eligible to apply for Singapore Permanent Residence (PTS Scheme) after 1–2 years of working on EP. Approval rate depends on profile, tech contribution, and demographic balance.",
        "language_requirements": "English is the official business and national working language. 100% English environment, zero foreign language barrier.",
        "family_mother_feasibility": "Outstanding: EP holders earning ≥ S$12,000/month can directly sponsor their mother/parents for a Long Term Visit Pass (LTVP / LTVP+), providing continuous legal residence with simple renewals. Just 4.5h direct flights to India.",
        "family_mother_badge": "Outstanding (Direct LTVP)",
        "quality_of_life_rank": "#1 in Asia (#42 Worldwide)",
        "happiness_rank": "#33 Worldwide · #1 in Asia (Score: 6.57)",
        "safety_score": "Top 3 Globally · Safest Country in Asia (Score: 88.5/100)",
        "retirement_suitability": "World-leading healthcare infrastructure (Gleneagles, Mount Elizabeth, SGH), barrier-free accessibility, excellent eldercare nursing facilities, peaceful park connectors, and 0% capital gains / estate tax.",
        "scenic_pollution_rating": "Famous 'Garden City' with 47% green cover (Gardens by the Bay, East Coast Park, Bukit Timah Nature Reserve). High tropical air quality with lush botanical greenery.",
        "peaceful_scenic_motivation": "The world's premier 'City in a Garden'—a tropical oasis of absolute personal safety, immaculate cleanliness, and peaceful urban design. Walk beneath the futuristic canopy of Gardens by the Bay, stroll the serene wooden boardwalks of MacRitchie Reservoir surrounded by rainforest, and unwind along East Coast Park's sea breeze.",
        "best_cities_states": "• **District 10 & 11 (Bukit Timah / Novena / Newton)**: Lush residential enclave nestled right next to Bukit Timah Nature Reserve and Singapore Botanic Gardens with quiet low-density green living.\n• **District 15 (East Coast / Marine Parade / Tanjong Rhu)**: Breezy seaside living with direct access to the 15km East Coast Park beach connector, cycling paths, and rich Indian expat conveniences.",
        "keep_in_mind_notes": "1) Year-round tropical humidity (28°C–34°C); 2) Private car ownership is world's most expensive due to 10-year COE (>S$100k certificate alone); 3) High condominium rental rates; 4) Strict civic regulations and fines (chewing gum ban, jaywalking, littering); 5) Fast-paced corporate work culture.",
        "interview_style_summary": "High-Speed Pragmatic Delivery, High-Scale Concurrency, Fintech/E-Commerce Scalability & Multi-Region Design",
        "interview_process_stages": "Stage 1: Recruiter Call (20m) → Stage 2: Online Assessment / Live Algorithmic & Problem Solving (60m) → Stage 3: Scalable Distributed Systems Design (60m) → Stage 4: VP of Engineering / Cross-Functional Leadership (45m)",
        "employer_behavior_culture": "Fast-paced, commercially sharp, and metric-oriented. Interviewers look for agility in shipping features while safeguarding systems against peak traffic spikes (e.g. 11.11 / flash sales / real-time payments).",
        "senior_8yoe_focus": "For 8+ YOE: Focus on distributed transactions (Saga, 2PC), multi-region active-active architectures, API latency SLA optimization, and leading multicultural teams across APAC.",
        "tax_breakdown_notes": "World-renowned low progressive personal income tax (2% to 22% top bracket; ~11.5% effective on S$170k). 0% capital gains tax and 0% foreign income remittance tax.",
        "tech_market_notes": "Premier APAC headquarters hub for ByteDance, Grab, Sea Group, Google, Meta, Stripe, Shopee, and top fintech & AI ventures.",
        "order_index": 5,
    },
    {
        "rank": 6,
        "country_name": "Switzerland",
        "flag_emoji": "🇨🇭",
        "summary_verdict": "World's highest net compensation, pristine alpine beauty & lowest European income taxes",
        "currency_code": "CHF",
        "currency_symbol": "CHF ",
        "exchange_rate_inr": 119.50,
        "salary_min": 120000.0,
        "salary_max": 180000.0,
        "salary_median": 145000.0,
        "estimated_tax_rate": 22.0,
        "monthly_expense_local": 4200.0,
        "sponsor_visa_pathway": "Swiss Work Permit (B-Permit / L-Permit) sponsored by Swiss employer. Requires quota allocation for specialized non-EU tech hires (salary typically > CHF 110k+).",
        "pr_criteria_timeline": "C-Permit (Permanent Settlement Permit) after 10 years of continuous residence (or fast-track after 5 years with German/French B1 integration and high continuous earnings).",
        "language_requirements": "English is 100% sufficient for tech engineering in Zurich, Geneva & Basel. German (Zurich) or French (Geneva/Lausanne) needed for daily civic administration and C-permit PR.",
        "family_mother_feasibility": "Immediate family reunification for spouse & minor children with unrestricted work rights. Parents can visit on 90-day Schengen visitor visas (permanent parent stay requires exceptional sole hardship proof).",
        "family_mother_badge": "Schengen Visitor Visa",
        "quality_of_life_rank": "🏆 #5 Worldwide (Numbeo 2026)",
        "happiness_rank": "🏆 #13 Worldwide (TheGlobalEconomy 2026 - Score: 6.94)",
        "safety_score": "Top 5 Globally · Near-Zero Violent Crime (Score: 84.5/100)",
        "retirement_suitability": "Gold-standard 3-pillar pension system (AHV/BVG/3a), world-renowned medical hospitals and private clinics, pristine mountain air, clean tranquil lakeside promenades.",
        "scenic_pollution_rating": "Pristine Alpine Wilderness (AQI < 8). The Matterhorn, Lake Lucerne, Lake Geneva, pure glacial drinking tap water, strictly preserved carbon-neutral nature reserves.",
        "peaceful_scenic_motivation": "The ultimate alpine paradise of serene lakes and snow-capped peaks. Live within reach of the crystal waters of Lake Zurich & Lake Lucerne, kayak in Lake Brienz, take weekend train escapes to car-free mountain havens like Zermatt, Lauterbrunnen, and Grindelwald, and breathe the purest mountain air in Europe (AQI < 8).",
        "best_cities_states": "• **Zurich (Canton Zurich)** & **Zug ('Crypto Valley')**: Premier European tech hub (Google EMEA Engineering HQ, Meta, Apple, IBM Research) with low cantonal tax rates (~18–22%), immaculate lake promenades, and 45-min access to alpine ski trails.\n• **Vaud / Geneva (Lake Geneva Arc: Lausanne & Geneva)**: French-speaking serenity, international diplomacy, world-class research (EPFL, CERN), and idyllic vineyards overlooking Lake Geneva and the French Alps.",
        "keep_in_mind_notes": "1) Annual non-EU work permit quotas (~8,500 total B/L permits per year for all third-country nationals); 2) Mandatory private basic health insurance (Krankenkasse) costs ~CHF 350–500/month per person with deductibles (Franchise); 3) High cost of dining out, domestic services, and groceries; 4) Extremely quiet rules (strict Ruhezeit after 10 PM and all day Sunday); 5) Standard 10-year timeline for non-EU to obtain C-Permit PR.",
        "interview_style_summary": "Engineering Excellence, Extreme Reliability, Algorithmic & Low-Latency Precision (Google Zurich / Big Tech / High-Performance Systems)",
        "interview_process_stages": "Stage 1: Recruiter Screen (30m) → Stage 2: Technical Phone Screen (DSA / Core Systems 45m) → Stage 3: Onsite Loop: 2x Algorithmic Coding + 2x Distributed System Design + 1x Leadership / Googleyness",
        "employer_behavior_culture": "Ultra-high engineering standards with low tolerance for superficial answers. Swiss and multinational panels value mathematical rigor, deep OS/network internals, clean code invariants, and structured edge-case analysis.",
        "senior_8yoe_focus": "For 8+ YOE: Focus on massive scale (multi-petabyte, billions of queries), distributed consensus algorithms (Raft/Paxos), fault domains, latency tail optimization (p99/p99.9), and senior architectural influence.",
        "tax_breakdown_notes": "Three-tier tax system: Direct Federal Tax (~0.77%–11.5%) + Cantonal Tax (e.g. Zurich ~13%, Zug ~8%) + Municipal Tax + Church Tax (optional). Effective tax on CHF 145k in Zurich is only ~21–23%.",
        "tech_market_notes": "Major global engineering hubs: Google Zurich (largest tech engineering center outside Mountain View), Meta, Apple, Microsoft, Disney Research, ABB, UBS/Credit Suisse tech.",
        "order_index": 6,
    },
    {
        "rank": 7,
        "country_name": "Ireland",
        "flag_emoji": "🇮🇪",
        "summary_verdict": "Very interesting native English-speaking European tech capital & fast 2-year PR",
        "currency_code": "EUR",
        "currency_symbol": "€",
        "exchange_rate_inr": 111.20,
        "salary_min": 90000.0,
        "salary_max": 130000.0,
        "salary_median": 105000.0,
        "estimated_tax_rate": 42.0,
        "monthly_expense_local": 2700.0,
        "sponsor_visa_pathway": "Critical Skills Employment Permit (CSEP) for software engineering roles with job offer ≥ €38k (or €64k+ for broader roles).",
        "pr_criteria_timeline": "Fastest PR in Europe: Transition from CSEP (Stamp 1) to Stamp 4 (Permanent Work/Residency without work permit) after only 2 years. Irish/EU Citizenship after 5 years.",
        "language_requirements": "Native English speaking country. 100% English, no foreign language required.",
        "family_mother_feasibility": "Immediate family reunification for spouse. Elderly Dependent Parent Visa (Stamp 0) is possible if sponsor has net disposable income > €60,000/yr (after tax) and private comprehensive health insurance.",
        "family_mother_badge": "Stamp 0 Pathway",
        "quality_of_life_rank": "#26 Worldwide",
        "happiness_rank": "#15 Worldwide (TheGlobalEconomy 2026 - Score: 6.89)",
        "safety_score": "High Safety · Global Peace Index Top 3 (Score: 74.0/100)",
        "retirement_suitability": "Warm, welcoming English-speaking community, beautiful peaceful coastal towns (Galway, Cork, Kerry), public/private dual healthcare model, serene rolling countryside.",
        "scenic_pollution_rating": "Known as the Emerald Isle: Lush green landscapes, Wild Atlantic Way coastal cliffs, exceptionally clean Atlantic maritime air (AQI < 10), very low industrial pollution.",
        "peaceful_scenic_motivation": "The Emerald Isle offers boundless tranquility and soul-soothing green beauty. Discover the rugged majesty of the Cliffs of Moher, the peaceful misty lakes of Killarney National Park, the rolling green valleys of Connemara, and the dramatic coastal serenity of the Wild Atlantic Way with pristine ocean air (AQI < 10).",
        "best_cities_states": "• **County Dublin South & Dún Laoghaire / Killiney**: Scenic seaside suburbs with direct 20-min DART rail to Dublin Silicon Docks (Google, Meta, Stripe), combining ocean breezes with peaceful suburban living.\n• **County Wicklow ('The Garden of Ireland')**: Misty green mountains, glacial lakes (Glendalough), and charming quiet towns located just 35 mins south of Dublin.",
        "keep_in_mind_notes": "1) Severe Dublin housing crunch with high rental bidding wars; 2) Public healthcare waiting lists (private health insurance like VHI/Laya is practically essential); 3) Frequent rain and gray skies year-round; 4) Public transport outside Dublin/Cork is sparse.",
        "interview_style_summary": "Silicon Valley Big Tech Standards (Dublin Silicon Docks) combined with European Pragmatism & Cloud Resilience",
        "interview_process_stages": "Stage 1: Recruiter Screen (30m) → Stage 2: Technical Coding Screen (45m) → Stage 3: Virtual Onsite: 2x Coding/DSA + 1x System Architecture + 1x Leadership & Culture Fit",
        "employer_behavior_culture": "Collaborative, friendly yet rigorous. Interviewers look for clear verbal articulation, STAR-format leadership examples, and ability to navigate ambiguity across global EMEA/US teams.",
        "senior_8yoe_focus": "For 8+ YOE: High emphasis on cross-functional alignment, designing resilient cloud-native architectures (AWS/GCP), incident management, and scaling systems for EMEA expansion.",
        "tax_breakdown_notes": "Standard 20% on first €42,000 + 40% higher rate on remainder + 4% PRSI (Social Insurance) + Universal Social Charge (USC 0.5% to 8%). Effective tax ~42%.",
        "tech_market_notes": "European Headquarters for Silicon Valley titans: Google, Meta, Apple, Stripe, AWS, Microsoft, TikTok, Hubspot, Workday in Dublin Silicon Docks.",
        "order_index": 7,
    },
    {
        "rank": 8,
        "country_name": "Sweden",
        "flag_emoji": "🇸🇪",
        "summary_verdict": "Exceptional work-life balance, lagom lifestyle, fast tech unicorn hub & 480-day parental leave",
        "currency_code": "SEK",
        "currency_symbol": "kr ",
        "exchange_rate_inr": 9.15,
        "salary_min": 650000.0,
        "salary_max": 950000.0,
        "salary_median": 780000.0,
        "estimated_tax_rate": 31.5,
        "monthly_expense_local": 22000.0,
        "sponsor_visa_pathway": "Swedish Work Permit (Arbetstillstånd) sponsored by employer with collective bargaining terms or EU Blue Card. Direct fast processing through certified employers.",
        "pr_criteria_timeline": "Permanent Residence (Permanent Uppehållstillstånd - PUT) after 4 years of working on a residence permit + Swedish language & self-sufficiency test. Citizenship after 5 years.",
        "language_requirements": "English is 100% fluent across the population (>90% EF English score). Swedish (Svenska) is optional for tech work, helpful for daily integration.",
        "family_mother_feasibility": "Spouse & minor children get immediate full work rights and subsidized world-class daycare. Parents can visit on 90-day Schengen visitor visas (permanent stay requires sole dependency proof).",
        "family_mother_badge": "Schengen Visitor Visa",
        "quality_of_life_rank": "#11 Worldwide",
        "happiness_rank": "🏆 #4 Worldwide (TheGlobalEconomy 2026 - Score: 7.35)",
        "safety_score": "High Safety · World Top 25 (Score: 74.0/100)",
        "retirement_suitability": "Universal public healthcare, generous multi-pillar pension system, extremely quiet green suburbs, high accessibility, safe cycling network.",
        "scenic_pollution_rating": "Pristine Air (AQI < 8). Stockholm 30,000-island archipelago, untouched Lapland pine forests, 100,000 clean freshwater lakes, strict Nordic eco-standards.",
        "peaceful_scenic_motivation": "Peaceful Scandinavian harmony and untouched archipelago tranquility. Live near the Stockholm Archipelago with 30,000 granite islands, kayak through tranquil mirror-calm lakes (Lake Mälaren, Lake Vättern), wander through silent pine and birch forests with universal 'Right to Roam' (Allemansrätten), and enjoy summer midnight sun.",
        "best_cities_states": "• **Stockholm County (Stockholm: Södermalm, Kungsholmen & Nacka / Lidingö archipelago)**: European tech startup unicorn capital (Spotify, Klarna, King, Mojang) built across 14 islands with immediate water and pine forest access.\n• **Skåne / Scania (Malmö & Lund)**: Mild southern climate, connected to Copenhagen via Øresund Bridge in 30 mins, vibrant tech incubator scene and quiet coastal living.",
        "keep_in_mind_notes": "1) Extreme winter darkness (Stockholm gets only ~6 hours daylight in Dec/Jan; requires Vitamin D); 2) Stockholm first-hand rental queue (Bostadskö) takes years—most expats use second-hand rentals (Andrahand); 3) High alcohol taxes with state stores (Systembolaget); 4) Reserved Nordic social culture (Lagom / personal space).",
        "interview_style_summary": "Consensus-Driven Engineering, High Autonomy, Clean Craftsmanship, Psychological Safety & Flat Hierarchies",
        "interview_process_stages": "Stage 1: Talent Acquisition Screen (30m) → Stage 2: Take-Home Code Project / Practical Pair Programming (60m) → Stage 3: Architecture Deep-Dive & Code Walkthrough (60m) → Stage 4: Team Culture, Values & Ways of Working (45m)",
        "employer_behavior_culture": "High emphasis on low ego ('Lagom' & humility), collaboration, and team cohesion. Interviewers evaluate how well you listen, how you receive constructive feedback, and whether you create inclusive environments.",
        "senior_8yoe_focus": "For 8+ YOE: Demonstrating how you build consensus across autonomous squads, technical coaching, sustainable engineering velocity, and pragmatic modular architectures.",
        "tax_breakdown_notes": "Municipal income tax (kommunalskatt) averages ~32%. State income tax (statlig inkomstskatt) is 20% on income above ~SEK 615k. Social security is primarily paid by the employer (~31.42%).",
        "tech_market_notes": "Tech unicorn powerhouse: Spotify, Klarna, King, Mojang (Minecraft), Ericsson, Truecaller, Tink, Einride, Polestar.",
        "order_index": 8,
    },
    {
        "rank": 9,
        "country_name": "Norway",
        "flag_emoji": "🇳🇴",
        "summary_verdict": "World's wealthiest sovereign wealth security, breathtaking fjords & unmatched work-life balance (37.5h week)",
        "currency_code": "NOK",
        "currency_symbol": "kr ",
        "exchange_rate_inr": 8.90,
        "salary_min": 750000.0,
        "salary_max": 1100000.0,
        "salary_median": 880000.0,
        "estimated_tax_rate": 34.0,
        "monthly_expense_local": 25000.0,
        "sponsor_visa_pathway": "Skilled Worker Residence Permit (Faglært) sponsored by a Norwegian employer with university degree or specialized IT qualifications.",
        "pr_criteria_timeline": "Permanent Residence Permit after 3 continuous years on skilled worker permit + passing Norwegian language test (A2/B1 level) & social studies exam. Citizenship after 7 years.",
        "language_requirements": "English proficiency is near 100% in tech companies & daily commerce. Norwegian (Norsk) required for permanent residency and local community integration.",
        "family_mother_feasibility": "Spouse and children receive immediate residence with full right to work. Parents can visit on 90-day Schengen visitor visas (permanent stay requires exceptional sole dependency).",
        "family_mother_badge": "Schengen Visitor Visa",
        "quality_of_life_rank": "🏆 #10 Worldwide (Numbeo 2026)",
        "happiness_rank": "🏆 #7 Worldwide (TheGlobalEconomy 2026 - Score: 7.26)",
        "safety_score": "Top 5 Globally · World's Lowest Crime (Score: 82.5/100)",
        "retirement_suitability": "Backed by the world's largest Government Pension Fund Global ($1.7 Trillion), world-class public healthcare, peaceful fjord-side towns, unmatched social safety net.",
        "scenic_pollution_rating": "Pristine Clean Air (AQI < 7). Dramatic glacial fjords (Geirangerfjord, Nærøyfjord), Northern Lights (Aurora Borealis), 85%+ EV clean transport adoption, pure mountain spring tap water.",
        "peaceful_scenic_motivation": "The ultimate dramatic nature sanctuary on Earth. Wake up to panoramic views of silent majestic fjords, crystal mountain lakes (Lake Mjøsa), towering waterfalls, and the dancing Northern Lights. Norway embraces Friluftsliv (open-air living), ensuring every citizen enjoys deep spiritual peace in boundless, untouched nature.",
        "best_cities_states": "• **Oslo (Viken / Oslo Fjord: Majorstuen, Grünerløkka & Bærum/Asker)**: Tech and financial capital (Vipps, Schibsted, Cognite, Oda, Kahoot!) combining modern urban efficiency with direct tram access to Oslomarka forests and island beaches.\n• **Vestland (Bergen)** & **Trøndelag (Trondheim)**: Bergen is the UNESCO fjord gateway surrounded by 7 scenic mountains; Trondheim is Norway's premier engineering and AI research hub (NTNU, Sintef).",
        "keep_in_mind_notes": "1) High cost of consumer goods, eating out, and groceries due to high VAT (25%) and import tariffs; 2) Long dark winter nights in winter months; 3) High precipitation in coastal cities (Bergen has ~200+ rainy days/yr); 4) Work permit processing through UDI requires strict degree verification.",
        "interview_style_summary": "Pragmatic Quality, Autonomous Squad Culture, Cloud-Native Architecture & Transparent Problem Solving",
        "interview_process_stages": "Stage 1: People & Culture Intro (30m) → Stage 2: Technical Discussion & Code Review (60m) → Stage 3: Scalable System Architecture (60m) → Stage 4: Management & Culture Fit (45m)",
        "employer_behavior_culture": "Direct, trustworthy, and informal. Norwegian companies value engineers who take full end-to-end ownership of services (DevOps / 'You build it, you run it'), communicate openly about risks, and respect work-life balance.",
        "senior_8yoe_focus": "For 8+ YOE: Operability, site reliability engineering (SRE), automated testing, data sovereignty, and empowering decentralized engineering teams.",
        "tax_breakdown_notes": "Base income tax (22%) + Social Security (Trygdeavgift ~7.8%) + Bracket Tax (Trinnskatt from 1.7% up to 17.6%). Effective tax rate on NOK 880k is ~33–35%.",
        "tech_market_notes": "Leading software, energy-tech, and AI hubs: Vipps, Schibsted, Cognite, Kahoot!, Oda, Gelato, Opera, Equinor Tech, DNB Tech.",
        "order_index": 9,
    },
    {
        "rank": 10,
        "country_name": "Australia",
        "flag_emoji": "🇦🇺",
        "summary_verdict": "Excellent long-term lifestyle, high compensation, and dedicated parent visas (Subclass 870)",
        "currency_code": "AUD",
        "currency_symbol": "A$",
        "exchange_rate_inr": 68.40,
        "salary_min": 150000.0,
        "salary_max": 200000.0,
        "salary_median": 170000.0,
        "estimated_tax_rate": 32.0,
        "monthly_expense_local": 4000.0,
        "sponsor_visa_pathway": "Subclass 482 (Skills in Demand / TSS Visa) sponsored by employer, Subclass 186 Employer Nomination PR, or Subclass 189/190 Points-Tested Independent PR.",
        "pr_criteria_timeline": "Employer-Sponsored PR (Subclass 186 TRT) after 2 years on Subclass 482 visa, or direct PR via Points-Tested stream (65+ points on age, experience, English, qualifications).",
        "language_requirements": "English (IELTS score 6.0–7.0+ or PTE Academic 65+ for skills assessment and PR points).",
        "family_mother_feasibility": "Dedicated Parent Visas: Subclass 870 Sponsored Parent (Temporary) Visa allows parents to live in Australia continuously for 3 or 5 years (renewable up to 10 years) without leaving. Also Contributory Parent PR (Subclass 143).",
        "family_mother_badge": "Subclass 870 (3-5 Yr Stay)",
        "quality_of_life_rank": "#14 Worldwide",
        "happiness_rank": "#11 Worldwide (TheGlobalEconomy 2026 - Score: 6.97)",
        "safety_score": "Very High Safety · Low Violent Crime (Score: 72.8/100)",
        "retirement_suitability": "Superb sunny retirement lifestyle, Medicare public healthcare + private hospital network, high quality aged care facilities, substantial Superannuation retirement nest egg.",
        "scenic_pollution_rating": "World-class pristine beaches, Great Barrier Reef, Blue Mountains, crystal clean oceanic air, sunny climate with >240 sunny days/yr.",
        "peaceful_scenic_motivation": "Sun-drenched coastal and mountain sanctuary. Wake up to the serene blue eucalyptus mists of the Blue Mountains, walk the powdery white sands of Byron Bay and Jervis Bay, explore the lush ancient Daintree Rainforest, or enjoy peaceful coastal vineyard walks in Margaret River with pure oceanic air.",
        "best_cities_states": "• **New South Wales (Sydney North Shore & Northern Beaches: Ryde, Manly, Hornsby)**: Excellent tech job market with leafy eucalyptus suburbs, harbour bays, and 30-min access to the Blue Mountains foothills.\n• **Queensland (Brisbane & Sunshine Coast / Gold Coast Hinterland)**: Warm year-round subtropical climate, lower housing costs, serene rainforest hinterlands, and pristine uncrowded beaches.",
        "keep_in_mind_notes": "1) Extreme geographic distance from Europe and North America (long flights, +4.5h to +5.5h vs IST); 2) Extreme UV index and sun intensity requiring daily SPF protection; 3) High housing purchase prices in Sydney and Melbourne; 4) Dynamic immigration policy changes for visa caps.",
        "interview_style_summary": "Values-Driven Practical Engineering ('Open company, no bullshit'), Collaborative Whiteboarding & End-to-End Ownership",
        "interview_process_stages": "Stage 1: Recruiter Screen (30m) → Stage 2: Practical Coding / System Walkthrough (60m) → Stage 3: System Architecture & Scalability (60m) → Stage 4: Company Values & Leadership Interview (45m)",
        "employer_behavior_culture": "Informal, down-to-earth, and allergic to corporate jargon. Interviewers appreciate authentic self-awareness, pragmatic problem-solving, and a focus on customer outcomes.",
        "senior_8yoe_focus": "For 8+ YOE: Designing for operability and observability (SLOs, alerting), reducing cognitive load for teams, managing technical debt pragmatically, and mentoring.",
        "tax_breakdown_notes": "Progressive resident tax rates (16% to 45%) + 2% Medicare levy. Employers contribute additional 11.5% Superannuation (retirement fund) on top of base salary.",
        "tech_market_notes": "Booming tech ecosystem in Sydney & Melbourne: Atlassian, Canva, Afterpay/Block, SafetyCulture, Airwallex, AWS, Google.",
        "order_index": 10,
    },
    {
        "rank": 11,
        "country_name": "New Zealand",
        "flag_emoji": "🇳🇿",
        "summary_verdict": "Pristine lifestyle, work-life balance, but smaller tech market size",
        "currency_code": "NZD",
        "currency_symbol": "NZ$",
        "exchange_rate_inr": 56.80,
        "salary_min": 130000.0,
        "salary_max": 170000.0,
        "salary_median": 148000.0,
        "estimated_tax_rate": 30.5,
        "monthly_expense_local": 3500.0,
        "sponsor_visa_pathway": "Accredited Employer Work Visa (AEWV) or Straight to Residence Visa via Green List Tier 1 (Software Engineers earning median wage).",
        "pr_criteria_timeline": "Direct PR on arrival via Green List Tier 1 Straight to Residence, or Skilled Migrant Category (SMC) 6-point system after 1–2 years of local employment.",
        "language_requirements": "English (IELTS 6.5 minimum or equivalent test).",
        "family_mother_feasibility": "Parent Resident Visa (annual ballot with income criteria) or Parent and Grandparent Visitor Visa (allows 6 months per entry, up to 18 months total in 3 years).",
        "family_mother_badge": "Parent Visitor Visa",
        "quality_of_life_rank": "#15 Worldwide",
        "happiness_rank": "#12 Worldwide (TheGlobalEconomy 2026 - Score: 6.95)",
        "safety_score": "Top 5 Global Peace Index · Peaceful & Safe (Score: 76.5/100)",
        "retirement_suitability": "Unmatched tranquility and slow-paced lifestyle, public healthcare system, clean unpolluted mountain/coastal towns (Queenstown, Nelson, Tauranga), friendly community vibes.",
        "scenic_pollution_rating": "100% Pure New Zealand: Majestic Southern Alps, crystalline glacial lakes, Milford Sound fjords, zero heavy industry pollution, among the cleanest air and water on Earth.",
        "peaceful_scenic_motivation": "The undisputed global capital for peace, clean air, and surreal natural beauty. Live surrounded by the snow-crowned Southern Alps, gaze upon the surreal turquoise waters of Lake Tekapo and Lake Wakatipu (Queenstown), kayak through the silent majesty of Milford Sound (Fiordland), and breathe the world's cleanest air among rolling green hills.",
        "best_cities_states": "• **Canterbury (Christchurch & Queenstown / Wanaka outskirts)**: The pinnacle of peace and dramatic alpine scenery—turquoise glacial lakes, Southern Alps, and pure mountain air.\n• **Auckland (North Shore: Devonport, Takapuna)**: Tech headquarters market with panoramic volcanic harbour views, clean coastal walks, and relaxed island ferry commutes.",
        "keep_in_mind_notes": "1) High cost of living and expensive imported consumer goods due to geographic isolation; 2) Located in the Pacific Ring of Fire (seismic earthquake risk); 3) Domestic flight dependency for inter-island travel; 4) Smaller local tech market with lower salary ceilings compared to Australia/US.",
        "interview_style_summary": "Pragmatic Problem-Solving, Team Cohesion, Clean Code & Versatile Full-Stack Systems",
        "interview_process_stages": "Stage 1: Initial Screen (30m) → Stage 2: Technical Pairing & Problem Solving (60m) → Stage 3: Architecture & System Overview (60m) → Stage 4: Team Fit & Culture (45m)",
        "employer_behavior_culture": "Supportive, collaborative, and team-first ('No heroes / tall poppy syndrome'). Interviewers value humility, curiosity, and adaptable engineers who can wear multiple hats.",
        "senior_8yoe_focus": "For 8+ YOE: Cloud cost optimization, pragmatic tech stack choices, team enablement, and building maintainable software with small, agile teams.",
        "tax_breakdown_notes": "Progressive income tax (10.5% to 39%) + ACC Earner's Levy (1.6%). No capital gains tax.",
        "tech_market_notes": "Specialized tech hubs in Auckland and Wellington: Xero, Pushpay, Rocket Lab, Trade Me, Datacom.",
        "order_index": 11,
    },
    {
        "rank": 12,
        "country_name": "Poland",
        "flag_emoji": "🇵🇱",
        "summary_verdict": "Premier high-growth tech hub in Central Europe, low living costs, booming R&D hubs & flat B2B tax",
        "currency_code": "PLN",
        "currency_symbol": "zł ",
        "exchange_rate_inr": 25.80,
        "salary_min": 190000.0,
        "salary_max": 320000.0,
        "salary_median": 240000.0,
        "estimated_tax_rate": 19.0,
        "monthly_expense_local": 6800.0,
        "sponsor_visa_pathway": "National Type D Work Visa / Temporary Residence and Work Permit (Karta Pobytu) or EU Blue Card (Niebieska Karta UE) sponsored by tech employer.",
        "pr_criteria_timeline": "EU Long-Term Resident Permit (Zezwolenie na pobyt rezydenta długoterminowego UE) after 5 continuous years of legal stay + Polish B1 language certificate. Polish citizenship after 3 years on PR.",
        "language_requirements": "English is 100% the working language in IT & global multinationals (Google, Microsoft, Snowflake, CD Projekt). Polish (Polski) needed for permanent residency.",
        "family_mother_feasibility": "Immediate family reunification for spouse & minor children on temporary residence. Parents can visit on 90-day Schengen visas (long-term parent stay requires proven economic dependency).",
        "family_mother_badge": "Schengen Visitor Visa",
        "quality_of_life_rank": "#36 Worldwide",
        "happiness_rank": "#26 Worldwide (TheGlobalEconomy 2026 - Score: 6.67)",
        "safety_score": "Very High Safety · Safest in Central Europe (Score: 75.8/100 · very low street crime)",
        "retirement_suitability": "Affordable private healthcare network (Medicover/Luxmed), low cost of living allowing substantial retirement wealth accumulation, picturesque historic towns, central European rail connectivity.",
        "scenic_pollution_rating": "Beautiful Tatra Mountains (Zakopane), pristine Masurian Lake District (2,000+ lakes), Baltic Sea beaches (Sopot/Gdańsk), clean green national parks (Białowieża ancient forest).",
        "peaceful_scenic_motivation": "Peaceful mountain peaks and thousands of mirror lakes. Explore the alpine splendor of the Tatra Mountains (Morskie Oko lake, Zakopane), sail across the serene Masurian Lake District surrounded by dense pine forests, walk the amber-sand beaches of the Baltic coast (Gdynia, Sopot), and stroll peaceful historic cobbled town squares.",
        "best_cities_states": "• **Masovian Voivodeship (Warsaw: Mokotów, Wilanów, Powiśle & Ursynów)**: The tech & financial capital of Central Europe (Google Cloud European HQ, Microsoft, Snowflake, Box, Samsung R&D) with green parks (Łazienki Park) and rapid modern transit.\n• **Lesser Poland / Małopolska (Kraków & Zakopane foothills)**: Historic cultural gem with a dense tech hub (Cisco, Google, Uber R&D, Motorola) and immediate 1-hour access to the dramatic Tatra Mountains.\n• **Lower Silesia (Wrocław & Trójmiasto - Gdańsk/Gdynia)**: Wrocław ('Venice of Poland' with 100+ bridges) and Gdańsk (breezy Baltic seaside tech cluster).",
        "keep_in_mind_notes": "1) Winter air quality in southern valleys during coal-heating season (improving rapidly with clean energy laws); 2) Complex administrative paperwork (Urząd Wojewódzki immigration office wait times for Karta Pobytu cards); 3) Slavic language with complex grammar (Polish B1 needed for 5-year PR); 4) Cold winters with temperatures between -5°C to -15°C.",
        "interview_style_summary": "Deep Technical & Algorithmic Rigor, R&D Engineering Standards, Strong CS Fundamentals & Fast Execution",
        "interview_process_stages": "Stage 1: HR Screening (30m) → Stage 2: Technical Screening (Live DSA / Problem Solving 60m) → Stage 3: Deep System Architecture & DB Internals (60m) → Stage 4: Engineering Manager Round (45m)",
        "employer_behavior_culture": "Technically profound and intellectually demanding. Polish R&D engineering centers (Google, Snowflake, Microsoft) place heavy weight on computer science fundamentals, algorithmic efficiency, and memory/CPU optimization.",
        "senior_8yoe_focus": "For 8+ YOE: Distributed storage engines, concurrency models, low-level performance profiling, and leading distributed scrum teams.",
        "tax_breakdown_notes": "Popular B2B contract model allows tech professionals to pay a flat 12% revenue tax (Ryczałt) or 19% linear tax + flat ZUS social contributions, leading to effective taxes under 18–20% and very high net savings.",
        "tech_market_notes": "Top European engineering hub for global giants: Google (Warsaw & Kraków), Microsoft, Snowflake, Amazon, Cisco, Intel (Gdańsk), CD Projekt Red, Allegro, Revolut.",
        "order_index": 12,
    },
]

