"""
North America Target Company Profiles Data Service.
Includes FAANG & Big Tech, Non-FAANG Tech & Scale-ups, and AllianceTek Inc (Malvern, PA) Client / Partner Ecosystem.
"""

from typing import Dict, List, Any


NA_TARGET_COMPANIES: List[Dict[str, Any]] = [
    # ══════════════════════════════════════════════════════════════════
    # 1. FAANG & TIER-1 BIG TECH
    # ══════════════════════════════════════════════════════════════════
    {
        "name": "Google",
        "category": "faang",
        "category_label": "FAANG & Big Tech",
        "flag": "🇺🇸 🇨🇦",
        "hubs": "Mountain View, NYC, Seattle, Waterloo, Montreal",
        "salary_range": "$280k – $420k TC",
        "salary_sub": "USD (C$220k – C$340k CAD) · Base $190k-$230k + RSU",
        "dsa": "Hard",
        "sd": "Heavy",
        "beh": "Googliness & Leadership",
        "visa": "H-1B, O-1, GTS (Canada 2-Wk)",
        "focus": "Spanner/Bigtable, concurrency, distributed query engines, clean code, scalable APIs, algorithmic speed",
        "alliancetek_relation": None,
    },
    {
        "name": "Meta",
        "category": "faang",
        "category_label": "FAANG & Big Tech",
        "flag": "🇺🇸",
        "hubs": "Menlo Park, NYC, Seattle, Austin",
        "salary_range": "$290k – $450k TC",
        "salary_sub": "USD · Base $200k-$240k + High RSU Initial & Refreshers",
        "dsa": "Hard (Fast)",
        "sd": "Heavy",
        "beh": "STAR / Fast Execution",
        "visa": "H-1B, O-1, EB-1/2",
        "focus": "High-speed 20-min coding, TAO / Memcached caching layers, live feed architecture, GraphQL, Cassandra",
        "alliancetek_relation": None,
    },
    {
        "name": "Amazon",
        "category": "faang",
        "category_label": "FAANG & Big Tech",
        "flag": "🇺🇸 🇨🇦",
        "hubs": "Seattle, Bay Area, NYC, Vancouver, Toronto",
        "salary_range": "$250k – $380k TC",
        "salary_sub": "USD (C$200k – C$320k CAD) · Base $180k-$210k + RSU/Bonus",
        "dsa": "Hard",
        "sd": "Heavy",
        "beh": "Bar Raiser (14 LPs)",
        "visa": "H-1B, L-1, GTS (Canada)",
        "focus": "Distributed scale, DynamoDB, AWS microservices, operational rigor, Customer Obsession STAR stories",
        "alliancetek_relation": None,
    },
    {
        "name": "Apple",
        "category": "faang",
        "category_label": "FAANG & Big Tech",
        "flag": "🇺🇸",
        "hubs": "Cupertino, Seattle, Austin, San Diego",
        "salary_range": "$260k – $390k TC",
        "salary_sub": "USD · Base $195k-$230k + RSU Equity",
        "dsa": "Med-Hard",
        "sd": "Heavy",
        "beh": "High Collaboration",
        "visa": "H-1B, O-1, L-1",
        "focus": "Cloud services infrastructure, high-scale storage, security, Python / C++ / Java / Swift, low-latency APIs",
        "alliancetek_relation": None,
    },
    {
        "name": "Netflix",
        "category": "faang",
        "category_label": "FAANG & Big Tech",
        "flag": "🇺🇸",
        "hubs": "Los Gatos, Los Angeles, Remote US",
        "salary_range": "$380k – $550k All-Cash",
        "salary_sub": "USD · Top of Market Total Cash Compensation Model",
        "dsa": "Medium",
        "sd": "Extremely Heavy",
        "beh": "Culture Memo & Freedom",
        "visa": "H-1B, O-1",
        "focus": "Chaos engineering, microservices resilience, high-throughput CDN, Java / Python / Go, distributed state",
        "alliancetek_relation": None,
    },
    {
        "name": "Microsoft",
        "category": "faang",
        "category_label": "FAANG & Big Tech",
        "flag": "🇺🇸 🇨🇦",
        "hubs": "Redmond, Bay Area, NYC, Vancouver Hub",
        "salary_range": "$240k – $360k TC",
        "salary_sub": "USD (C$190k – C$290k CAD) · Base $175k-$215k + RSU + Bonus",
        "dsa": "Med-Hard",
        "sd": "Heavy",
        "beh": "Growth Mindset / STAR",
        "visa": "L-1, H-1B, GTS (Vancouver)",
        "focus": "Azure cloud services, C# / Java / Python, distributed microservices, enterprise scale, AI integration",
        "alliancetek_relation": None,
    },

    # ══════════════════════════════════════════════════════════════════
    # 2. NON-FAANG TECH GIANTS, SCALE-UPS & FINTECH
    # ══════════════════════════════════════════════════════════════════
    {
        "name": "Stripe",
        "category": "non_faang",
        "category_label": "Non-FAANG & Scale-ups",
        "flag": "🇺🇸 🇨🇦",
        "hubs": "San Francisco, Seattle, Toronto, Remote",
        "salary_range": "$300k – $460k TC",
        "salary_sub": "USD (C$240k – C$360k CAD) · Base $200k-$240k + Equity",
        "dsa": "Practical Debug",
        "sd": "Heavy",
        "beh": "High Rigor & Transparency",
        "visa": "H-1B, O-1, GTS (Canada)",
        "focus": "Idempotent payment APIs, distributed transactions, database consistency, live bug fixing, observability",
        "alliancetek_relation": None,
    },
    {
        "name": "Shopify",
        "category": "non_faang",
        "category_label": "Non-FAANG & Scale-ups",
        "flag": "🇨🇦 🇺🇸",
        "hubs": "Toronto, Waterloo, Ottawa, Remote North America",
        "salary_range": "C$200k – C$320k TC",
        "salary_sub": "CAD ($220k – $340k USD Flex) · Base + Flex Comp",
        "dsa": "Medium / Pair",
        "sd": "Heavy",
        "beh": "Life Story Interview",
        "visa": "Direct GTS (Canada 2-Wk), TN/H-1B",
        "focus": "E-commerce scale, Ruby / Python / Go, Kafka, Black Friday resilience, merchant empathy, paired refactoring",
        "alliancetek_relation": None,
    },
    {
        "name": "Databricks",
        "category": "non_faang",
        "category_label": "Non-FAANG & Scale-ups",
        "flag": "🇺🇸 🇨🇦",
        "hubs": "San Francisco, Seattle, Vancouver, Remote",
        "salary_range": "$310k – $480k TC",
        "salary_sub": "USD (C$250k – C$380k CAD) · Heavy Pre-IPO / Equity Value",
        "dsa": "Hard",
        "sd": "Heavy",
        "beh": "First Principles & STAR",
        "visa": "H-1B, O-1, GTS (Canada)",
        "focus": "Distributed query engines, Spark internals, C++ / Rust / Scala / Python, lakehouse delta storage",
        "alliancetek_relation": None,
    },
    {
        "name": "Snowflake",
        "category": "non_faang",
        "category_label": "Non-FAANG & Scale-ups",
        "flag": "🇺🇸 🇨🇦",
        "hubs": "San Mateo, Bellevue, Toronto",
        "salary_range": "$300k – $470k TC",
        "salary_sub": "USD (C$240k – C$370k CAD) · Base $190k-$230k + RSU",
        "dsa": "Hard",
        "sd": "Heavy",
        "beh": "Medium-High",
        "visa": "H-1B, GTS (Canada)",
        "focus": "Cloud data warehousing, decoupled compute & storage, distributed concurrency, metadata engines, C++ / Java",
        "alliancetek_relation": None,
    },
    {
        "name": "Uber",
        "category": "non_faang",
        "category_label": "Non-FAANG & Scale-ups",
        "flag": "🇺🇸 🇨🇦",
        "hubs": "San Francisco, Seattle, Toronto",
        "salary_range": "$270k – $410k TC",
        "salary_sub": "USD (C$210k – C$320k CAD) · Base $185k-$225k + RSU",
        "dsa": "Hard",
        "sd": "Heavy",
        "beh": "High / Customer Focused",
        "visa": "H-1B, GTS (Canada)",
        "focus": "Geospatial indexing (H3), real-time marketplace dispatch, high-QPS Kafka event bus, Go / Java / Python",
        "alliancetek_relation": None,
    },
    {
        "name": "1Password",
        "category": "non_faang",
        "category_label": "Non-FAANG & Scale-ups",
        "flag": "🇨🇦 🇺🇸",
        "hubs": "Toronto, Vancouver, Ottawa, Remote US/Canada",
        "salary_range": "C$170k – C$260k TC",
        "salary_sub": "CAD ($180k – $270k USD Remote) · Base + Stock Options",
        "dsa": "Medium",
        "sd": "Heavy",
        "beh": "Culture & Empathy",
        "visa": "Direct GTS (Canada), Fast LMIA",
        "focus": "Zero-knowledge security, Go / Rust / Python, end-to-end encryption, multi-tenant cloud storage",
        "alliancetek_relation": None,
    },
    {
        "name": "Salesforce",
        "category": "non_faang",
        "category_label": "Non-FAANG & Scale-ups",
        "flag": "🇺🇸 🇨🇦",
        "hubs": "San Francisco, Seattle, Toronto, Remote",
        "salary_range": "$240k – $370k TC",
        "salary_sub": "USD (C$190k – C$280k CAD) · Base $180k-$210k + RSU",
        "dsa": "Medium-Hard",
        "sd": "Heavy",
        "beh": "Ohana Culture & Trust",
        "visa": "H-1B, L-1, GTS (Canada)",
        "focus": "Multi-tenant enterprise cloud, real-time data engines, REST / GraphQL APIs, microservices, Java / Python",
        "alliancetek_relation": None,
    },
    {
        "name": "Capital One",
        "category": "non_faang",
        "category_label": "Non-FAANG & Scale-ups",
        "flag": "🇺🇸 🇨🇦",
        "hubs": "McLean VA, Richmond VA, NYC, Toronto",
        "salary_range": "$185k – $275k TC",
        "salary_sub": "USD (C$160k – C$240k CAD) · Base $165k-$210k + 15-20% Bonus",
        "dsa": "Medium (Practical)",
        "sd": "Heavy / AWS",
        "beh": "STAR / Case Behavioral",
        "visa": "H-1B, L-1, GTS (Toronto)",
        "focus": "100% AWS cloud native, serverless & containers, Kafka streaming, FinTech credit APIs, Python / Java / Go",
        "alliancetek_relation": None,
    },
    {
        "name": "Walmart Global Tech",
        "category": "non_faang",
        "category_label": "Non-FAANG & Scale-ups",
        "flag": "🇺🇸 🇨🇦",
        "hubs": "Bentonville AR, Sunnyvale CA, Toronto Hub",
        "salary_range": "$190k – $285k TC",
        "salary_sub": "USD · Base $160k-$200k + 20% Bonus + RSU",
        "dsa": "Medium-Hard",
        "sd": "Heavy",
        "beh": "Servant Leadership",
        "visa": "H-1B, L-1, GTS (Toronto)",
        "focus": "Massive supply chain scale, inventory graph engines, high-throughput checkout APIs, Spring Boot / Python",
        "alliancetek_relation": None,
    },
    {
        "name": "JPMorgan Chase & Co",
        "category": "non_faang",
        "category_label": "Non-FAANG & Scale-ups",
        "flag": "🇺🇸",
        "hubs": "New York, Jersey City, Plano TX, Wilmington DE",
        "salary_range": "$180k – $265k TC",
        "salary_sub": "USD · Base $160k-$200k + Annual Performance Bonus ($30k-$60k)",
        "dsa": "Medium (Practical)",
        "sd": "Heavy",
        "beh": "Finance Integrity & STAR",
        "visa": "H-1B, L-1 (Major Sponsor in DE/NY)",
        "focus": "Low-latency trading & payments, cloud modernization (AWS/Private Cloud), data security, Spring / Python / C++",
        "alliancetek_relation": None,
    },
    {
        "name": "Intuit",
        "category": "non_faang",
        "category_label": "Non-FAANG & Scale-ups",
        "flag": "🇺🇸 🇨🇦",
        "hubs": "Mountain View CA, San Diego CA, Toronto",
        "salary_range": "$220k – $340k TC",
        "salary_sub": "USD (C$180k – C$270k CAD) · Base $175k-$210k + RSU",
        "dsa": "Medium",
        "sd": "Heavy",
        "beh": "Design for Delight (D4D)",
        "visa": "H-1B, GTS (Canada)",
        "focus": "FinTech tax & accounting automation (TurboTax/QuickBooks), GenAI agents, distributed data pipelines, Spring / Python",
        "alliancetek_relation": None,
    },
    {
        "name": "Cisco Systems",
        "category": "non_faang",
        "category_label": "Non-FAANG & Scale-ups",
        "flag": "🇺🇸 🇨🇦",
        "hubs": "San Jose CA, RTP NC, Kanata/Ottawa, Toronto",
        "salary_range": "$195k – $290k TC",
        "salary_sub": "USD (C$160k – C$240k CAD) · Base $165k-$200k + RSU + Bonus",
        "dsa": "Medium",
        "sd": "Heavy",
        "beh": "Collaboration / STAR",
        "visa": "H-1B, L-1, GTS (Canada)",
        "focus": "Cloud networking, telemetry & observability (Splunk/AppDynamics), security APIs, Python / Go / C++",
        "alliancetek_relation": None,
    },
    {
        "name": "Oracle / OCI",
        "category": "non_faang",
        "category_label": "Non-FAANG & Scale-ups",
        "flag": "🇺🇸 🇨🇦",
        "hubs": "Austin TX, Seattle WA, Vancouver, Remote",
        "salary_range": "$210k – $340k TC",
        "salary_sub": "USD (C$175k – C$270k CAD) · Base $170k-$210k + RSU",
        "dsa": "Med-Hard",
        "sd": "Heavy (Cloud Infra)",
        "beh": "Medium",
        "visa": "H-1B, L-1, GTS (Canada)",
        "focus": "Oracle Cloud Infrastructure (OCI) compute/storage, distributed DB orchestration, high-speed virtual networking",
        "alliancetek_relation": None,
    },
    {
        "name": "Optum / UnitedHealth Group",
        "category": "non_faang",
        "category_label": "Non-FAANG & Scale-ups",
        "flag": "🇺🇸",
        "hubs": "Eden Prairie MN, Boston MA, Basking Ridge NJ, Remote",
        "salary_range": "$170k – $250k TC",
        "salary_sub": "USD · Base $155k-$190k + 15-20% Bonus + RSU",
        "dsa": "Medium (Practical)",
        "sd": "Heavy (Data/APIs)",
        "beh": "Compassion & STAR",
        "visa": "H-1B, L-1, Green Card",
        "focus": "Healthcare analytics at national scale, FHIR interoperability, HIPAA secure APIs, Python / Spark / Java / AWS",
        "alliancetek_relation": None,
    },
    {
        "name": "Adobe",
        "category": "non_faang",
        "category_label": "Non-FAANG & Scale-ups",
        "flag": "🇺🇸",
        "hubs": "San Jose CA, San Francisco, Seattle, Remote",
        "salary_range": "$230k – $360k TC",
        "salary_sub": "USD · Base $180k-$215k + RSU",
        "dsa": "Medium-Hard",
        "sd": "Heavy",
        "beh": "High",
        "visa": "H-1B, O-1, L-1",
        "focus": "Creative Cloud / Experience Platform, real-time multimedia processing, GenAI Firefly pipelines, C++ / Python / Java",
        "alliancetek_relation": None,
    },

    # ══════════════════════════════════════════════════════════════════
    # 3. THIRD-PARTY VENDOR PAYROLL & REGIONAL CLIENT NETWORK (ALLIANCETEK / DENALI)
    # ══════════════════════════════════════════════════════════════════
    {
        "name": "AllianceTek / Denali (3rd-Party Payroll)",
        "category": "alliancetek",
        "category_label": "Vendor Staffing & Clients",
        "flag": "🇺🇸 🇮🇳",
        "hubs": "Malvern PA (US Office) / Ahmedabad (Denali Delivery)",
        "salary_range": "$75k – $105k / yr",
        "salary_sub": "($40 – $55/hr W2) · Third-Party Vendor Middleman Rate for US Client Placements (after agency cut)",
        "dsa": "Practical / Arrays & HashMaps",
        "sd": "Practical Architecture",
        "beh": "Client Delivery & Agility",
        "visa": "Vendor H-1B / 3rd-Party Staffing",
        "focus": "Full-stack enterprise app development, Python (FastAPI/Django), REST APIs, database queries, client staff augmentation",
    },
    {
        "name": "Vanguard Group",
        "category": "alliancetek",
        "category_label": "Vendor Staffing & Clients",
        "flag": "🇺🇸",
        "hubs": "Malvern, PA & Charlotte NC",
        "salary_range": "$175k – $255k TC",
        "salary_sub": "USD · Direct Full-Time ($155k-$190k base + bonus) / Staffing Vendor Contractor",
        "dsa": "Medium (Practical)",
        "sd": "Heavy (FinTech Cloud)",
        "beh": "Client-First & Collaboration",
        "visa": "H-1B, Green Card, Third-Party Staffing",
        "focus": "Massive investment management platforms ($8T+ AUM), AWS microservices, Python / Java / Spring Boot, event streaming, strict financial compliance & disaster recovery",
    },
    {
        "name": "Comcast / NBCUniversal Tech",
        "category": "alliancetek",
        "category_label": "Vendor Staffing & Clients",
        "flag": "🇺🇸",
        "hubs": "Philadelphia, PA & Greater PA Corridor",
        "salary_range": "$180k – $260k TC",
        "salary_sub": "USD · Direct Full-Time ($155k-$195k base + bonus) / Vendor Staff Augmentation",
        "dsa": "Medium (Practical)",
        "sd": "Heavy (Streaming / Edge)",
        "beh": "STAR / Culture Fit",
        "visa": "H-1B, L-1, Consulting Placements",
        "focus": "High-throughput streaming telemetry, Peacock / Xfinity video backends, Python / Go / Java, Kubernetes orchestration, distributed edge caching",
    },
    {
        "name": "SAP America",
        "category": "alliancetek",
        "category_label": "Vendor Staffing & Clients",
        "flag": "🇺🇸",
        "hubs": "Newtown Square, PA (PA Corridor)",
        "salary_range": "$190k – $290k TC",
        "salary_sub": "USD · Direct Full-Time / Vendor Integration Engagements",
        "dsa": "Medium-Hard",
        "sd": "Heavy (Enterprise B2B)",
        "beh": "High Enterprise Professionalism",
        "visa": "H-1B, L-1, Direct Sponsorship",
        "focus": "Enterprise cloud ERP, SAP HANA database engines, B2B integration microservices, multi-tenant cloud scalability, Python / Java / C++",
    },
    {
        "name": "AmerisourceBergen / Cencora",
        "category": "alliancetek",
        "category_label": "Vendor Staffing & Clients",
        "flag": "🇺🇸",
        "hubs": "Conshohocken, PA",
        "salary_range": "$170k – $245k TC",
        "salary_sub": "USD · Direct Full-Time / IT Vendor Staff Augmentation",
        "dsa": "Medium (Practical)",
        "sd": "Heavy (Supply Chain / Data)",
        "beh": "Healthcare Integrity & STAR",
        "visa": "H-1B, Staff Augmentation SOWs",
        "focus": "Fortune 10 pharmaceutical logistics & distribution, real-time inventory tracking (Kafka), healthcare data privacy (HIPAA), Python / SQL / AWS data lakes",
    },
    {
        "name": "Independence Blue Cross (IBX)",
        "category": "alliancetek",
        "category_label": "Vendor Staffing & Clients",
        "flag": "🇺🇸",
        "hubs": "Philadelphia, PA & Blue Bell PA",
        "salary_range": "$160k – $230k TC",
        "salary_sub": "USD · Direct Full-Time / Vendor Contractor Placements",
        "dsa": "Practical / Medium",
        "sd": "Heavy (Healthcare Systems)",
        "beh": "STAR / Member Focus",
        "visa": "H-1B Transfer, IT Consulting SOWs",
        "focus": "Healthcare insurance digital portals, claims processing pipelines, patient API integration (FHIR/HL7), Python / SQL / Oracle, data warehouse modernization",
    },
    {
        "name": "Lincoln Financial Group",
        "category": "alliancetek",
        "category_label": "Vendor Staffing & Clients",
        "flag": "🇺🇸",
        "hubs": "Radnor, PA & Remote",
        "salary_range": "$165k – $240k TC",
        "salary_sub": "USD · Direct Full-Time / IT Staffing Augmentation",
        "dsa": "Medium (Practical)",
        "sd": "Practical Scale / Cloud",
        "beh": "Financial Service Ethics",
        "visa": "H-1B, Staff Augmentation",
        "focus": "InsurTech digital workflows, automated underwriting engines, cloud microservices, REST APIs, Python / Java / Snowflake data reporting",
    },
]


def get_na_company_profiles() -> List[Dict[str, Any]]:
    """Returns the full list of North America target companies."""
    return NA_TARGET_COMPANIES


def get_company_stats() -> Dict[str, Any]:
    """Returns summary stats for the target companies table."""
    total = len(NA_TARGET_COMPANIES)
    faang_count = sum(1 for c in NA_TARGET_COMPANIES if c["category"] == "faang")
    non_faang_count = sum(1 for c in NA_TARGET_COMPANIES if c["category"] == "non_faang")
    alliancetek_count = sum(1 for c in NA_TARGET_COMPANIES if c["category"] == "alliancetek")

    return {
        "total": total,
        "faang_count": faang_count,
        "non_faang_count": non_faang_count,
        "alliancetek_count": alliancetek_count,
    }
