"""add_alternate_title_and_url_to_dsa_problems

Revision ID: 6f31de6a10f9
Revises: 2d03546bfe17
Create Date: 2026-08-14 16:49:44.299295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f31de6a10f9'
down_revision: Union[str, None] = '2d03546bfe17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dsa_problems', sa.Column('alternate_title', sa.String(length=300), nullable=True))
    op.add_column('dsa_problems', sa.Column('alternate_url', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dsa_problems', 'alternate_url')
    op.drop_column('dsa_problems', 'alternate_title')
    # ### end Alembic commands ###
